// ═══════════════════════════════════════════════════
// PLAN DATA – Letzte Aktualisierung: 1. August 2026
// typ: compound | isolation | core  → bestimmt Pausenzeit
// Beim Review: aktuell/ziel/zielgewicht von Claude angepasst
// ═══════════════════════════════════════════════════
const PLAN = {
  version: "August 2026 (Rev. 01.08.)",
  Push: [
    { name:"Chest Press", muskel:"Brust · Schulter · Trizeps", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"4×8–12 @ 55 kg", zielgewicht:55, ziel:"55 kg festigen → 4×12",
      schritte:["Rücken fest ans Polster – nicht abheben","3 Sek runter, explosiv hoch","Ellenbogen nicht ganz durchstrecken","Brust am engsten Punkt 1 Sek zusammendrücken"],
      tipp:"52,5 → 55 kg im Juli. Erst 4×12 @ 55 kg sauber, dann 57,5 kg." },
    { name:"Pectoral Fly", muskel:"Brust (Isolation)", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×12 @ 57,5 kg", zielgewicht:60, ziel:"→ 60 kg testen",
      schritte:["Arme immer leicht gebeugt – Ellenbogenschutz!","Langsam zur Mitte, 1–2 Sek halten","Brust aktiv zusammenquetschen","Kontrolliert öffnen bis zur vollen Dehnung"],
      tipp:"9 Einheiten im Juli ohne Steigerung, 3×12 stabil. Jetzt 60 kg testen – Reps fallen anfangs auf 10." },
    { name:"Shoulder Press", muskel:"Schulter vorne/mitte · Trizeps", typ:"compound",
      saetze:3, repzone:"8–12", aktuell:"3×10 @ 30 kg", zielgewicht:30, ziel:"3×12 @ 30 kg festigen",
      schritte:["Core anspannen, kein Hohlkreuz","Griffe auf Ohrhöhe – drücken bis kurz vor Streckung","Langsam runter, Schultern nicht hochziehen","Backoff: 4. Satz @ 27,5 kg bis zum Versagen"],
      tipp:"Maschine kennt nur 27,5 oder 30 kg. 27,5 war im Juni bereits 3×12 – zurückgehen wäre ein Rückschritt. 30 kg mit 8–10 Wdh liegt im Zielfenster. Drei Hebel: (1) in jeder zweiten Push-Einheit an erste Position, sonst ist die vordere Schulter durch Chest Press + Fly vorermüdet, (2) 120 Sek Pause statt 90, (3) Backoff-Satz @ 27,5 kg." },
    { name:"Triceps Press", muskel:"Trizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 95 kg", zielgewicht:null, ziel:"Einstellung prüfen – nicht erhöhen",
      schritte:["Aufrecht sitzen, Rücken fest ans Polster","Griffe auf Schulterhöhe, Ellenbogen nah am Körper","Explosiv drücken bis zur vollen Streckung – Trizeps anspannen","3 Sek zurück – kontrolliert, nicht fallen lassen"],
      tipp:"80 → 95 kg in vier Wochen bei durchgehend 3×12 ist als reiner Kraftzuwachs unplausibel. Vor der nächsten Einheit Sitz- und Hebeleinstellung prüfen und notieren, sonst ist die Zahl keine Vergleichsgröße mehr." },
    { name:"Rear Delt Fly", muskel:"Hintere Schulter · Rhomboiden", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×12 @ 55 kg", zielgewicht:55, ziel:"55 kg festigen → 3×12–15",
      schritte:["Sitz umdrehen oder Reverse-Modus","Arme leicht gebeugt, Schulterblätter zusammenziehen","Langsam und kontrolliert – kein Schwung"],
      tipp:"Wichtig für Schulterbalance und Haltung." },
    { name:"Lateral Raise", muskel:"Mittlere Schulter", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×8 @ 7,5–8 kg (links schmerzhaft)", zielgewicht:null, ziel:"Nicht forcieren – erst 3×12 schmerzfrei",
      schritte:["Arme seitlich bis Schulterhöhe heben","Leicht gebeugte Ellenbogen, Daumen leicht nach unten"],
      tipp:"Links weiter gereizt trotz Manschette – nicht forcieren. Erst wenn 3×12 schmerzfrei laufen, wieder aufbauen." },
    { name:"Wadenheben (HSR-Block)", muskel:"Gastrocnemius · Soleus · Achillessehne", typ:"compound",
      saetze:3, repzone:"6–8", aktuell:"3×8 @ 90 kg", zielgewicht:90, ziel:"Frequenzblock – kein eigenes Progressionsziel",
      schritte:["3 Sek runter, am tiefsten Punkt direkt umkehren","3 Sek hoch, volle Streckung","Kein Halten unten, kein Abfedern"],
      tipp:"Kurzer Zusatzblock am Ende der Einheit. Zweck ist Frequenz (3×/Woche), nicht Volumen – Sehnenadaptation braucht wiederholte Reize. Steigerung nur am Legs-Tag entscheiden, hier immer das dort gültige Gewicht verwenden." }
  ],
  Pull: [
    { name:"Latzug", muskel:"Latissimus · Bizeps", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"3×12 @ 80 kg", zielgewicht:80, ziel:"80 kg festigen – 24-h-Reaktion beobachten",
      schritte:["Griff breiter als Schultern (Obergriff)","Stange zur oberen Brust – Ellenbogen nach unten/hinten","Brust nach vorne öffnen – nicht zurückschaukeln!","Latissimus am Ende 1 Sek zusammenziehen","Kontrolliert hoch – volle Streckung"],
      tipp:"Freigegeben am 30.07. Bedingung: Daumen NICHT in den Griff einschlagen (Vier-Finger-Griff). Läuft seit 10.07. wieder, 70 → 80 kg. Steuerung über die 24-Stunden-Reaktion, nicht über das Gefühl während der Einheit – die Injektion vom 20.07. kann Schmerzsignale noch maskieren." },
    { name:"Ruderzug", muskel:"Mittlerer Rücken · Trapezius · Bizeps", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"Im Juli nicht trainiert", zielgewicht:35, ziel:"Wiedereinstieg 3×12 @ ~35 kg",
      schritte:["Aufrecht sitzen – nicht nach hinten lehnen!","Griff zur Brust-/Bauchmitte – Ellenbogen nah am Körper","Schulterblätter am Ende 1–2 Sek zusammendrücken","Kontrolliert zurück"],
      tipp:"Freigegeben am 30.07., Vier-Finger-Griff. Als einzige Übung im Juli komplett ausgefallen – konservativ bei ~35 kg einsteigen, langsame Exzentrik, dann in 5-kg-Schritten nach 24-h-Reaktion." },
    { name:"Straight Arm Pulldown", muskel:"Latissimus (kein Grip)", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12–13 @ 28,75 kg", zielgewicht:28.75, ziel:"28,75 kg festigen, 3×12 sauber",
      schritte:["Kabelzug, Seil oder gerade Stange auf Augenhöhe","Arme gestreckt – Stange/Seil mit gestreckten Armen nach unten/hinten drücken","Latissimus am Ende zusammenziehen","Keine Ellenbogenbeugung – das ist der Trick"],
      tipp:"32,5 kg am 23.07. war zu schwer (8/5/5). Bei 28,75 kg bleiben. Kein Grip nötig – Open-Hand oder Seil. Bleibt als Ergänzung im Plan, auch jetzt wo Latzug wieder läuft." },
    { name:"Dual Pulley Roll", muskel:"Latissimus · Rumpfstabilität", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×8–10 @ 35 kg", zielgewicht:35, ziel:"35 kg festigen → 3×12",
      schritte:["Zwei Kabelzüge auf Schulterhöhe, je eine Umlenkrolle","Einen nach dem anderen nach unten ziehen – alternierend","Rumpf stabil halten, nicht schaukeln","Kontrollierte Bewegung, Lat aktiviert halten"],
      tipp:"Am 29.07. auf 8/8/10 gefallen – nicht erhöhen, erst 3×12 @ 35 kg sauber." },
    { name:"Bizepscurl", muskel:"Bizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×8–12 @ 21 kg", zielgewicht:21, ziel:"21 kg festigen → 3×12",
      schritte:["Oberarme fixiert – nur Unterarme bewegen","Ganz unten strecken, oben 1 Sek halten","3–4 Sek absenken = mehr Muskelreiz","Kein Rückenschwung!"],
      tipp:"Freigegeben am 30.07., aber nur Maschine/Kabel und ohne Daumen im Griff. Am 29.07. auf 10/9/7 gefallen – nicht erhöhen, erst 3×12 @ 21 kg sauber." },
    { name:"Face Pulls", muskel:"Hintere Schulter · Rotatorenmanschette", typ:"isolation",
      saetze:3, repzone:"15", aktuell:"3×12–15 @ 21,25 kg", zielgewicht:null, ziel:"3×15, Tempo halten",
      schritte:["Kabelzug mit Seilaufsatz auf Augenhöhe","Seil zur Stirn – Ellenbogen nach außen/oben"],
      tipp:"Schützt das Schultergelenk langfristig." },
    { name:"Wadenheben (HSR-Block)", muskel:"Gastrocnemius · Soleus · Achillessehne", typ:"compound",
      saetze:3, repzone:"6–8", aktuell:"3×8 @ 90 kg", zielgewicht:90, ziel:"Frequenzblock – kein eigenes Progressionsziel",
      schritte:["3 Sek runter, am tiefsten Punkt direkt umkehren","3 Sek hoch, volle Streckung","Kein Halten unten, kein Abfedern"],
      tipp:"Kurzer Zusatzblock am Ende der Einheit. Zweck ist Frequenz (3×/Woche), nicht Volumen – Sehnenadaptation braucht wiederholte Reize. Steigerung nur am Legs-Tag entscheiden, hier immer das dort gültige Gewicht verwenden." }
  ],
  Legs: [
    { name:"Rückenstrecker", muskel:"Erector spinae (unterer Rücken)", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×15 @ 10–15 kg", zielgewicht:20, ziel:"15 kg festigen → 20 kg",
      schritte:["Aufrecht in die Maschine, Rücken flach anlegen","Langsam nach vorne beugen – volle Dehnung spüren","Kontrolliert zurückstrecken bis zur aufrechten Position","Keine Überstreckung am Ende – Spannung halten"],
      tipp:"Feste erste Position der Einheit – im Juli nicht geloggt. Warm-up für die Wirbelsäule und Verletzungsschutz bei allen Beinübungen." },
    { name:"Beinpresse", muskel:"Quadrizeps · Gesäß · Hamstrings", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"4×11–12 @ 130 kg", zielgewicht:130, ziel:"130 kg festigen → 4×12",
      schritte:["Füße schulterbreit, Zehen leicht nach außen (15–30°)","Knie immer in Richtung Zehen – nie einknicken!","Bis ca. 90° Kniewinkel – Rücken bleibt am Sitz","Explosiv drücken, kurz vor voller Streckung stoppen"],
      tipp:"Knie links: Füße etwas höher auf die Platte stellen." },
    { name:"Hip Thrust", muskel:"Gluteus maximus (großer Gesäßmuskel)", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 85 kg", zielgewicht:90, ziel:"→ 90 kg",
      schritte:["Rücken gegen Polsterung, Füße schulterbreit auf dem Boden","Hüfte nach oben drücken bis Körper eine Linie bildet","Oben 1–2 Sek halten – Gesäß maximal anspannen","Kontrolliert runter – Gesäß berührt nicht den Boden"],
      tipp:"Falls kein Hip Thrust Gerät: Beinpresse mit Füßen sehr hoch und weit außen auf der Platte als Alternative – deutlich mehr Gluteus maximus Aktivierung." },
    { name:"Beinstrecker", muskel:"Quadrizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×11–12 @ 72 kg", zielgewicht:72, ziel:"72 kg festigen → 3×12",
      schritte:["Langsam strecken, oben 1–2 Sek halten und Quad anspannen","3–4 Sek zurück – nie fallen lassen"],
      tipp:"Max 113 kg = viel Potenzial. Bei Kniebeschwerden → Beinpresse statt." },
    { name:"Beinbeuger", muskel:"Hamstrings (Isolation)", typ:"isolation",
      saetze:3, repzone:"12", aktuell:"3×8–11 @ 60 kg", zielgewicht:60, ziel:"60 kg festigen → 3×12",
      schritte:["Oberschenkel fest auf Polsterung – nicht abheben!","Ferse zur Gesäßfalte, oben 1–2 Sek halten","3–4 Sek langsam strecken – Absenkphase ist entscheidend"],
      tipp:"50 → 60 kg im Juli, zuletzt 11/10/8. Nicht erhöhen, erst 3×12 @ 60 kg. Langsame Absenkphase bringt mehr Reiz als die Aufwärtsbewegung." },
    { name:"Hip Abduction", muskel:"Gluteus medius/minimus (seitliches Gesäß)", typ:"isolation",
      saetze:3, repzone:"15–20", aktuell:"3×15 @ 80 kg", zielgewicht:82.5, ziel:"→ 82,5 kg",
      schritte:["Aufrecht sitzen, Core angespannt","Beine langsam nach außen – Endpunkt 1–2 Sek halten","Kontrolliert zurück – nicht einfedern","Direkt weiter zur Adduktion, ohne Pause"],
      tipp:"Als Superset mit Hip Adduktion ohne Pause dazwischen – Agonist und Antagonist behindern sich nicht, spart 4–5 Min bei gleichem Reiz. Im Juli aus Zeitgründen ausgefallen." },
    { name:"Hip Adduktion", muskel:"Adduktoren (Innenseite Oberschenkel)", typ:"isolation",
      saetze:3, repzone:"15–20", aktuell:"3×20 @ 80 kg", zielgewicht:85, ziel:"→ 85 kg",
      schritte:["Aufrecht sitzen, Beine außen in die Polster","Beine kontrolliert nach innen zusammenführen","Am engsten Punkt 1–2 Sek halten","Langsam öffnen – nicht einfedern lassen"],
      tipp:"Zweiter Teil des Supersets mit Hip Abduction. Pause erst nach beiden Übungen. Wichtig für Kniestabilität." },
    { name:"Wadenheben (HSR)", muskel:"Gastrocnemius · Soleus · Achillessehne", typ:"compound",
      saetze:4, repzone:"6–8", aktuell:"3×8 @ 90 kg (Heavy Slow Resistance)", zielgewicht:90, ziel:"90 kg festigen, 4×8 – Steuerung über Morgensteifigkeit",
      schritte:["Nur Vorderfuß auf der Platte – Ferse hängt frei","3 Sek kontrolliert runter bis zur vollen Dehnung","Am tiefsten Punkt NICHT halten – direkt umkehren, ohne Abfedern","3 Sek hoch bis zur vollen Streckung","Volle ROM (Midportion-Tendinopathie – keine Einschränkung nötig)"],
      tipp:"Umstellung 01.08. wegen Achillessehnen-Tendinopathie (Midportion). Statt 3×20 @ 130 kg jetzt 3–4×6–8 @ 90 kg mit 3/3-Tempo – Sehnen adaptieren auf Zeit unter Spannung und Last, nicht auf Wiederholungszahl. 3×/Woche: am Legs-Tag plus als kurzer Block am Ende der Push+Pull-Einheiten. Steuerung: Morgensteifigkeit täglich in Minuten im Gewicht-Tab eintragen. Gleich oder fallend = Last passt. Steigend = letzte Einheit zurücknehmen. Unter 10 Min über mehrere Tage = Last darf hoch. Rückkehr zu höherem Volumen erst nach 4–6 Wochen stabiler Werte – und dann über Last, nicht über Wiederholungen." },
    { name:"Bauch gerade", muskel:"Rectus abdominis", typ:"core",
      saetze:3, repzone:"15–20", aktuell:"3×13–20 @ 53 kg (Reps schwanken)", zielgewicht:55, ziel:"3×15–20 @ 53 kg festigen → 55 kg",
      schritte:["Bauchmuskeln aktiv zusammenziehen – nicht mit dem Rücken drücken","Langsam, kontrolliert, oben 1 Sek halten"],
      tipp:"Reps schwanken noch – erst 3×15–20 @ 53 kg festigen, dann 55 kg. Max ist 70 kg." },
    { name:"Reverse Crunches", muskel:"Untere Bauchmuskeln", typ:"core",
      saetze:3, repzone:"15–20", aktuell:"3×15–20 @ Bodyweight", zielgewicht:null, ziel:"3×20 gefestigt – ggf. leichte Zusatzlast",
      schritte:["Captain's Chair: Unterarme auf die Polster, Rücken an die Rücklehne","Beine hängen lassen – Knie leicht gebeugt","Knie kontrolliert zur Brust ziehen – Hüfte rollt leicht nach oben","Langsam absenken – volle Streckung, Spannung halten"],
      tipp:"Captain's Chair seit 30.07. wieder freigegeben – Boden oder Captain's Chair, freie Wahl. Am Captain's Chair Unterarme belasten, nicht die Hände (De Quervain). Kein Schwung – Bewegung kommt aus dem Bauch." },
    { name:"Bauch seitlich", muskel:"Obliques", typ:"core",
      saetze:3, repzone:"20–24", aktuell:"Ersetzt durch Oblique Crunch (Hammer Strength)", zielgewicht:null, ziel:"Nur noch als Fallback, wenn HS-Maschine belegt",
      schritte:["Abwechselnd links/rechts – 4 Sek pro Seite","Bewegung aus dem Rumpf, nicht aus den Schultern"],
      tipp:"Seit Juli durch die Hammer-Strength-Maschine ersetzt – dort ist Progression über das Maschinenmaximum hinaus möglich. Nur noch Fallback." },
    { name:"Oblique Crunch (Hammer Strength)", muskel:"Obliques · Rectus abdominis", typ:"core",
      saetze:3, repzone:"12–15", aktuell:"3×15–20 @ 12,5 kg", zielgewicht:15, ziel:"→ 15 kg",
      schritte:["Seitlich einstellen – Schulterpolster fest anlegen","Rumpf diagonal einrollen – Schulter Richtung gegenüberliegender Hüfte","Am tiefsten Punkt 1 Sek halten, Obliques aktiv anspannen","Langsam zurück – Spannung halten, nicht zurückfallen lassen","Seite wechseln – beide Seiten gleiche Wiederholungszahl"],
      tipp:"Plate-loaded = Progression über Stufe 12 hinaus möglich. Kraft kommt aus dem Rumpf, nicht aus den Armen – Hände nur locker anlegen, Handgelenk neutral halten (De Quervain). Links mit weniger Gewicht starten, falls nötig." }
  ]
};

// PAUSE bleibt in index.html – hier nur die Plan-Daten.

// Lädt das Daily-Modul nach (Kalorien-Haken + Morgensteifigkeit).
// Liegt hier, weil GitHub keine Teil-Updates erlaubt und index.html
// dadurch unangetastet bleibt. Beim nächsten index.html-Commit sauber
// als eigenes <script>-Tag dorthin ziehen und diese Zeile entfernen.
document.head.appendChild(Object.assign(document.createElement("script"), { src: "daily.js" }));
