// ═══════════════════════════════════════════════════
// PLAN DATA – Letzte Aktualisierung: 24. Juli 2026
// typ: compound | isolation | core  → bestimmt Pausenzeit
// Beim Review: aktuell/ziel/zielgewicht von Claude angepasst
// ═══════════════════════════════════════════════════
const PLAN = {
  version: "Juli 2026 (Rev. 24.07.)",
  Push: [
    { name:"Chest Press", muskel:"Brust · Schulter · Trizeps", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"4×12 @ 50 kg", zielgewicht:52.5, ziel:"→ 52,5 kg testen",
      schritte:["Rücken fest ans Polster – nicht abheben","3 Sek runter, explosiv hoch","Ellenbogen nicht ganz durchstrecken","Brust am engsten Punkt 1 Sek zusammendrücken"],
      tipp:"4×12 @ 50 kg sauber – jetzt 52,5 kg testen. Reps fallen anfangs auf 8–10, das ist normal." },
    { name:"Pectoral Fly", muskel:"Brust (Isolation)", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×12–15 @ 55 kg", zielgewicht:57.5, ziel:"→ 57,5 kg testen (Reps fallen anfangs auf 12)",
      schritte:["Arme immer leicht gebeugt – Ellenbogenschutz!","Langsam zur Mitte, 1–2 Sek halten","Brust aktiv zusammenquetschen","Kontrolliert öffnen bis zur vollen Dehnung"],
      tipp:"Technik vor Gewicht. Dehnung am weitesten Punkt spüren." },
    { name:"Shoulder Press", muskel:"Schulter vorne/mitte · Trizeps", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 27,5 kg sauber", zielgewicht:28.75, ziel:"Zwischenschritt 28,75 kg → dann 30 kg",
      schritte:["Core anspannen, kein Hohlkreuz","Griffe auf Ohrhöhe – drücken bis kurz vor Streckung","Langsam runter, Schultern nicht hochziehen"],
      tipp:"30 kg direkt war nur 3×8. Deshalb Zwischenschritt 28,75 kg, erst dann 30 kg." },
    { name:"Triceps Press", muskel:"Trizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 80 kg", zielgewicht:82.5, ziel:"→ 82,5 kg",
      schritte:["Aufrecht sitzen, Rücken fest ans Polster","Griffe auf Schulterhöhe, Ellenbogen nah am Körper","Explosiv drücken bis zur vollen Streckung – Trizeps anspannen","3 Sek zurück – kontrolliert, nicht fallen lassen"],
      tipp:"Sehr gute Progression: 65→80 kg. Bei 3×12 @ 80 kg → 82,5 kg." },
    { name:"Rear Delt Fly", muskel:"Hintere Schulter · Rhomboiden", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×12–13 @ 50 kg", zielgewicht:52.5, ziel:"→ 52,5 kg",
      schritte:["Sitz umdrehen oder Reverse-Modus","Arme leicht gebeugt, Schulterblätter zusammenziehen","Langsam und kontrolliert – kein Schwung"],
      tipp:"Wichtig für Schulterbalance und Haltung." },
    { name:"Lateral Raise", muskel:"Mittlere Schulter", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×8 @ 7,5–8 kg (links schmerzhaft)", zielgewicht:null, ziel:"Nicht forcieren – erst 3×12 schmerzfrei",
      schritte:["Arme seitlich bis Schulterhöhe heben","Leicht gebeugte Ellenbogen, Daumen leicht nach unten"],
      tipp:"Links weiter gereizt trotz Manschette – nicht forcieren. Erst wenn 3×12 schmerzfrei laufen, wieder aufbauen." }
  ],
  Pull: [
    { name:"Latzug", muskel:"Latissimus · Bizeps", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"⚠️ Pausiert (De Quervain) → Straight Arm Pulldown ~30 kg · Dual Pulley Roll 30 kg", zielgewicht:65, ziel:"3–4×8–12 @ 65 kg (nach Ortho-Freigabe 30.07.)",
      schritte:["Griff breiter als Schultern (Obergriff)","Stange zur oberen Brust – Ellenbogen nach unten/hinten","Brust nach vorne öffnen – nicht zurückschaukeln!","Latissimus am Ende 1 Sek zusammenziehen","Kontrolliert hoch – volle Streckung"],
      tipp:"Aktuell ersetzt durch Straight Arm Pulldown (3×12 @ ~30 kg) und Dual Pulley Roll (3×12 @ 30 kg) – kein Grip/Handgelenkdruck. Kortison-Injektion am 20.07.; Freigabe erst im Termin am 30.07." },
    { name:"Ruderzug", muskel:"Mittlerer Rücken · Trapezius · Bizeps", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"⚠️ Pausiert (De Quervain)", zielgewicht:50, ziel:"3–4×10–12 @ 50 kg (nach Ortho-Freigabe 30.07.)",
      schritte:["Aufrecht sitzen – nicht nach hinten lehnen!","Griff zur Brust-/Bauchmitte – Ellenbogen nah am Körper","Schulterblätter am Ende 1–2 Sek zusammendrücken","Kontrolliert zurück"],
      tipp:"Pausiert bis zur Freigabe am 30.07. Dann wieder aufnehmen und Gewicht auf 10–12 Wdh anpassen." },
    { name:"Straight Arm Pulldown", muskel:"Latissimus (kein Grip)", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ ~30 kg (pendelt 28,75–32,5)", zielgewicht:30, ziel:"30 kg festigen, 3×12 sauber",
      schritte:["Kabelzug, Seil oder gerade Stange auf Augenhöhe","Arme gestreckt – Stange/Seil mit gestreckten Armen nach unten/hinten drücken","Latissimus am Ende zusammenziehen","Keine Ellenbogenbeugung – das ist der Trick"],
      tipp:"De Quervain-Alternative zu Latzug: kein Grip nötig, kein Handgelenkdruck. Open-Hand oder Seil nutzen." },
    { name:"Dual Pulley Roll", muskel:"Latissimus · Rumpfstabilität", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 30 kg", zielgewicht:32.5, ziel:"→ 32,5 kg",
      schritte:["Zwei Kabelzüge auf Schulterhöhe, je eine Umlenkrolle","Einen nach dem anderen nach unten ziehen – alternierend","Rumpf stabil halten, nicht schaukeln","Kontrollierte Bewegung, Lat aktiviert halten"],
      tipp:"Gute Ergänzung zum Straight Arm Pulldown. Trainiert auch Rumpfstabilität." },
    { name:"Bizepscurl", muskel:"Bizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 19 kg sauber (von 22 reduziert)", zielgewicht:null, ziel:"19 kg halten bis Ortho-Freigabe 30.07.",
      schritte:["Oberarme fixiert – nur Unterarme bewegen","Ganz unten strecken, oben 1 Sek halten","3–4 Sek absenken = mehr Muskelreiz","Kein Rückenschwung!"],
      tipp:"Von 22 auf 19 kg reduziert – saubere Ausführung, Handgelenk schonen. Nach der Kortison-Injektion vom 20.07. nicht erhöhen; Aufbau erst nach der Freigabe am 30.07." },
    { name:"Face Pulls", muskel:"Hintere Schulter · Rotatorenmanschette", typ:"isolation",
      saetze:3, repzone:"15", aktuell:"3×12–15 @ 21,25 kg", zielgewicht:null, ziel:"3×15, Tempo halten",
      schritte:["Kabelzug mit Seilaufsatz auf Augenhöhe","Seil zur Stirn – Ellenbogen nach außen/oben"],
      tipp:"Schützt das Schultergelenk langfristig." }
  ],
  Legs: [
    { name:"Rückenstrecker", muskel:"Erector spinae (unterer Rücken)", typ:"isolation",
      saetze:3, repzone:"12–15", aktuell:"3×15 @ 10–15 kg", zielgewicht:20, ziel:"15 kg festigen → 20 kg",
      schritte:["Aufrecht in die Maschine, Rücken flach anlegen","Langsam nach vorne beugen – volle Dehnung spüren","Kontrolliert zurückstrecken bis zur aufrechten Position","Keine Überstreckung am Ende – Spannung halten"],
      tipp:"Wichtig für Verletzungsschutz bei allen Beinübungen. Am Anfang der Einheit als Warm-up für die Wirbelsäule." },
    { name:"Beinpresse", muskel:"Quadrizeps · Gesäß · Hamstrings", typ:"compound",
      saetze:4, repzone:"8–12", aktuell:"4×12 @ 120 kg", zielgewicht:125, ziel:"→ 125 kg",
      schritte:["Füße schulterbreit, Zehen leicht nach außen (15–30°)","Knie immer in Richtung Zehen – nie einknicken!","Bis ca. 90° Kniewinkel – Rücken bleibt am Sitz","Explosiv drücken, kurz vor voller Streckung stoppen"],
      tipp:"Knie links: Füße etwas höher auf die Platte stellen." },
    { name:"Hip Thrust", muskel:"Gluteus maximus (großer Gesäßmuskel)", typ:"compound",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 75 kg", zielgewicht:80, ziel:"→ 80 kg",
      schritte:["Rücken gegen Polsterung, Füße schulterbreit auf dem Boden","Hüfte nach oben drücken bis Körper eine Linie bildet","Oben 1–2 Sek halten – Gesäß maximal anspannen","Kontrolliert runter – Gesäß berührt nicht den Boden"],
      tipp:"Falls kein Hip Thrust Gerät: Beinpresse mit Füßen sehr hoch und weit außen auf der Platte als Alternative – deutlich mehr Gluteus maximus Aktivierung." },
    { name:"Beinstrecker", muskel:"Quadrizeps (Isolation)", typ:"isolation",
      saetze:3, repzone:"10–12", aktuell:"3×12 @ 60 kg", zielgewicht:62.5, ziel:"→ 62,5 kg",
      schritte:["Langsam strecken, oben 1–2 Sek halten und Quad anspannen","3–4 Sek zurück – nie fallen lassen"],
      tipp:"Max 113 kg = viel Potenzial. Bei Kniebeschwerden → Beinpresse statt." },
    { name:"Beinbeuger", muskel:"Hamstrings (Isolation)", typ:"isolation",
      saetze:3, repzone:"12", aktuell:"3×12 @ 50 kg sauber", zielgewicht:52.5, ziel:"→ 52,5 kg",
      schritte:["Oberschenkel fest auf Polsterung – nicht abheben!","Ferse zur Gesäßfalte, oben 1–2 Sek halten","3–4 Sek langsam strecken – Absenkphase ist entscheidend"],
      tipp:"Langsame Absenkphase bringt mehr Reiz als die Aufwärtsbewegung." },
    { name:"Hip Abduction", muskel:"Gluteus medius/minimus (seitliches Gesäß)", typ:"isolation",
      saetze:3, repzone:"15–20", aktuell:"3×15 @ 80 kg", zielgewicht:82.5, ziel:"→ 82,5 kg",
      schritte:["Aufrecht sitzen, Core angespannt","Beine langsam nach außen – Endpunkt 1–2 Sek halten","Kontrolliert zurück – nicht einfedern"],
      tipp:"Trainiert die seitliche Gesäßpartie – wichtig für Hüftstabilität." },
    { name:"Hip Adduktion", muskel:"Adduktoren (Innenseite Oberschenkel)", typ:"isolation",
      saetze:3, repzone:"15–20", aktuell:"3×20 @ 80 kg", zielgewicht:85, ziel:"→ 85 kg",
      schritte:["Aufrecht sitzen, Beine außen in die Polster","Beine kontrolliert nach innen zusammenführen","Am engsten Punkt 1–2 Sek halten","Langsam öffnen – nicht einfedern lassen"],
      tipp:"Direkt nach Hip Abduction – Agonist und Antagonist im Block. Wichtig für Kniestabilität." },
    { name:"Wadenheben", muskel:"Gastrocnemius · Soleus", typ:"isolation",
      saetze:3, repzone:"15–20", aktuell:"3×20 @ 125 kg", zielgewicht:130, ziel:"→ 130 kg",
      schritte:["Nur Vorderfuß auf der Platte – Ferse hängt frei","Volle Streckung auf Zehenspitzen – 1–2 Sek halten","Ferse tief runter – volle Dehnung, langsam"],
      tipp:"Waden reagieren gut auf hohes Gewicht und langsames Tempo." },
    { name:"Bauch gerade", muskel:"Rectus abdominis", typ:"core",
      saetze:3, repzone:"15–20", aktuell:"3×13–20 @ 53 kg (Reps schwanken)", zielgewicht:55, ziel:"3×15–20 @ 53 kg festigen → 55 kg",
      schritte:["Bauchmuskeln aktiv zusammenziehen – nicht mit dem Rücken drücken","Langsam, kontrolliert, oben 1 Sek halten"],
      tipp:"Reps schwanken noch – erst 3×15–20 @ 53 kg festigen, dann 55 kg. Max ist 70 kg." },
    { name:"Reverse Crunches", muskel:"Untere Bauchmuskeln", typ:"core",
      saetze:3, repzone:"15–20", aktuell:"3×20 @ Bodyweight (Captain's Chair)", zielgewicht:null, ziel:"3×20 gefestigt – ggf. leichte Zusatzlast",
      schritte:["Captain's Chair: Unterarme auf die Polster, Rücken an die Rücklehne","Beine hängen lassen – Knie leicht gebeugt","Knie kontrolliert zur Brust ziehen – Hüfte rollt leicht nach oben","Langsam absenken – volle Streckung, Spannung halten"],
      tipp:"Trainiert die unteren Bauchmuskeln, die die Crunch-Maschine kaum erreicht. Kein Schwung – Bewegung kommt aus dem Bauch." },
    { name:"Bauch seitlich", muskel:"Obliques", typ:"core",
      saetze:3, repzone:"20–24", aktuell:"3×24 @ Stufe 12 (Maschinen-Max)", zielgewicht:null, ziel:"Tempo 4 Sek/Seite; Umstieg Hammer Strength nach Freigabe",
      schritte:["Abwechselnd links/rechts – 4 Sek pro Seite","Bewegung aus dem Rumpf, nicht aus den Schultern"],
      tipp:"Am Maschinenmaximum: Tempo als Progression. 4 Sek pro Seite." },
    { name:"Oblique Crunch (Hammer Strength)", muskel:"Obliques · Rectus abdominis", typ:"core",
      saetze:3, repzone:"12–15", aktuell:"3×12–15 @ 10 kg (beide Seiten gleich)", zielgewicht:12.5, ziel:"3×15 @ 10 kg sauber, dann 12,5 kg",
      schritte:["Seitlich einstellen – Schulterpolster fest anlegen","Rumpf diagonal einrollen – Schulter Richtung gegenüberliegender Hüfte","Am tiefsten Punkt 1 Sek halten, Obliques aktiv anspannen","Langsam zurück – Spannung halten, nicht zurückfallen lassen","Seite wechseln – beide Seiten gleiche Wiederholungszahl"],
      tipp:"Plate-loaded = Progression über Stufe 12 hinaus möglich. Kraft kommt aus dem Rumpf, nicht aus den Armen – Hände nur locker anlegen, Handgelenk neutral halten (De Quervain). Links mit weniger Gewicht starten, falls nötig." }
  ]
};

// PAUSE bleibt in index.html – hier nur die Plan-Daten.
